# Numpy Basics <hr style="border:2px solid #ff0000 "><hr>

<b>Daniel A Udasco</b>
<br>Comp Eng Tech Student

# Imports and Packages

In [91]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array - Scalar

In [2]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [4]:
np.shape(my_array)

(3,)

# 2D Array - Vector

In [9]:
my_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.shape(my_array)

(3, 3)

# 3D Array - Matrix

In [18]:
my_array = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]])
my_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
np.shape(my_array)

(3, 3, 3)

# 4D Array - Tensor

In [33]:
my_array = np.array([[[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]],
                     
                     [[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]],
                     
                     [[[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]],
                     [[1,2,3],[4,5,6],[7,8,9]]]]
)
my_array

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [36]:
np.shape(my_array)

(3, 3, 3, 3)

# Measures of Central Tendency

In [65]:
# Jaguar vs Panther
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])

resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [66]:
np.shape(resistance)

(2, 11)

In [81]:
# Mean
res_mean = np.nanmean(resistance, axis=1)
res_mean[0]

np.float64(9.399999999999999)

In [82]:
print(f'Jaguar:{res_mean[0]:.2f} ohms')
print(f'Panther:{res_mean[1]:.2f} ohms')

Jaguar:9.40 ohms
Panther:10.75 ohms


In [83]:
# Mean
res_median = np.nanmedian(resistance, axis=1)
res_median[0]

np.float64(9.8)

In [84]:
print(f'Jaguar:{res_median[0]:.2f} ohms')
print(f'Panther:{res_median[1]:.2f} ohms')

Jaguar:9.80 ohms
Panther:9.55 ohms


In [86]:
# Mode
res_mode = stats.mode(resistance, axis=1)
res_mode

NameError: name 'stats' is not defined

In [96]:
jag_res = resistance[0]

print("Jaguar Mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar Mode:
9.8 ohms
10.4 ohms


In [98]:
pan_res = resistance[1]

print("Panther Mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther Mode:
9.1 ohms


In [102]:
# Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [106]:
print(f'Jaguar: {res_range[0]:.2f} ohms')
print(f'Panther: {res_range[1]:.2f} ohms')

Jaguar: 8.00 ohms
Panther: 10.90 ohms


In [108]:
# IQR
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [109]:
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [ ]:
print(f'Jaguar IQR: {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR: {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR: 1.05 ohms
Jaguar IQR: 1.50 ohms


In [116]:
res_var = np.nanvar(resistance, ddof=1, axis=1)
res_var

array([ 4.86      , 11.08277778])

In [ ]:
print(f'Jaguar Variance: {res_var[0]:.2f} ohms')
print(f'Panther Variance: {res_var[1]:.2f} ohms')

Jaguar IQR: 4.86 ohms
Panther IQR: 11.08 ohms


In [118]:
res_std = np.nanstd(resistance, ddof=1, axis=1)
res_std

array([2.20454077, 3.32908062])

In [119]:
print(f'Jaguar Standard Deviation: {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation: {res_std[1]:.2f} ohms')

Jaguar Standard Deviation: 2.20 ohms
Panther Standard Deviation: 3.33 ohms
